import { q, type CategoryPoolDef } from '../types.ts';

/** General UX and design categories. Three questions per difficulty. */

export const lawsOfUx: CategoryPoolDef = {
  id: 'laws-of-ux',
  title: 'Laws of UX',
  description: 'Name the law, effect, or principle.',
  type: 'text',
  group: 'general',
  questions: [
    q(1, 'The more choices you offer, the longer it takes to decide.', "Hick's Law"),
    q(1, 'The time to hit a target depends on its size and its distance.', "Fitts's Law"),
    q(1, 'Users spend most of their time on other sites, so they expect yours to work the same way.', "Jakob's Law"),
    q(2, 'Miller said working memory holds about this many items, plus or minus two.', 'Seven'),
    q(2, 'Objects placed near each other are perceived as a group.', 'Law of Proximity'),
    q(2, 'People perceive attractive designs as easier to use.', 'Aesthetic-Usability Effect'),
    q(3, 'Every system has some complexity that cannot be removed, only moved.', "Tesler's Law (Conservation of Complexity)"),
    q(3, 'People judge an experience mostly by its most intense moment and how it ended.', 'Peak-End Rule'),
    q(3, 'Users remember the first and last items in a series best.', 'Serial Position Effect'),
    q(4, 'Productivity soars when a system responds in under this many milliseconds (Doherty Threshold).', '400 milliseconds'),
    q(4, 'When several similar objects are shown, the one that differs is the one remembered.', 'Von Restorff Effect (Isolation Effect)'),
    q(4, 'The closer people get to a goal, the faster they work toward it.', 'Goal-Gradient Effect'),
    q(5, 'People remember unfinished or interrupted tasks better than completed ones.', 'Zeigarnik Effect'),
    q(5, 'Be liberal in what you accept and conservative in what you send.', "Postel's Law"),
    q(5, 'Any task will inflate until all of the available time is spent.', "Parkinson's Law"),
  ],
  dailyDoubles: [
    q(3, "Roughly 80% of the effects come from 20% of the causes.", "Pareto Principle"),
    q(3, "Elements inside a shared boundary are perceived as a group.", "Law of Common Region"),
    q(4, "People see complex or ambiguous images in their simplest form.", "Law of Prägnanz"),
    q(4, "Among competing explanations, prefer the one with the fewest assumptions.", "Occam's Razor"),
    q(5, "Elements that are visually connected seem more related than those that are not.", "Law of Uniform Connectedness"),
    q(5, "Users skip the manual and start using software right away.", "Paradox of the Active User"),
  ],
};

export const accessibility: CategoryPoolDef = {
  id: 'accessibility',
  title: 'Accessibility',
  description: 'Standards, numbers, and the craft of inclusive design.',
  type: 'text',
  group: 'general',
  questions: [
    q(1, 'The HTML attribute that gives an image its text alternative.', 'alt'),
    q(1, 'What the acronym WCAG stands for.', 'Web Content Accessibility Guidelines'),
    q(1, 'The number in the shorthand "a11y" stands for this.', 'The 11 letters between the "a" and the "y"'),
    q(2, 'The minimum contrast ratio for normal body text at WCAG AA.', '4.5:1'),
    q(2, 'The HTML element that should name a form input.', '<label>'),
    q(2, 'The key that moves focus to the next interactive element.', 'Tab'),
    q(3, 'The ARIA attribute that tells screen readers to announce changes in a region.', 'aria-live'),
    q(3, 'The minimum contrast ratio for large text at WCAG AA.', '3:1'),
    q(3, 'The ARIA attribute that hides an element from assistive technology.', 'aria-hidden'),
    q(4, 'The minimum target size, in CSS pixels, required by WCAG 2.2 at level AA.', '24 by 24'),
    q(4, 'The contrast ratio required for normal text at WCAG AAA.', '7:1'),
    q(4, 'The year WCAG 2.2 became an official W3C recommendation.', '2023'),
    q(5, 'The four WCAG principles spell out this acronym.', 'POUR: Perceivable, Operable, Understandable, Robust'),
    q(5, 'The "first rule of ARIA."', "Don't use ARIA if a native HTML element can do the job"),
    q(5, 'Content must not flash more than this many times in any one second.', 'Three'),
  ],
  dailyDoubles: [
    q(3, "At regular weight, \"large text\" starts at this size.", "18pt (24px)"),
    q(3, "The ARIA attribute that links an input to its help or error text.", "aria-describedby"),
    q(4, "The WCAG version that added \"Target Size (Minimum).\"", "WCAG 2.2"),
    q(4, "The conformance level that requires captions on prerecorded video.", "Level A"),
    q(5, "The success criterion that WCAG 2.2 removed.", "4.1.1 Parsing"),
    q(5, "The success criterion number for Non-text Contrast.", "1.4.11"),
  ],
};

export const designHistoryAndType: CategoryPoolDef = {
  id: 'design-history-type',
  title: 'Design History & Type',
  description: 'Legends, movements, and letterforms.',
  type: 'text',
  group: 'general',
  questions: [
    q(1, 'The German art school Walter Gropius founded in 1919.', 'The Bauhaus'),
    q(1, 'The typeface category with small strokes finishing the ends of letters.', 'Serif'),
    q(1, 'The vertical space between lines of text, named after strips of metal.', 'Leading (line height)'),
    q(2, 'Adjusting the space between one specific pair of letters.', 'Kerning'),
    q(2, 'Dieter Rams was chief designer at this German company.', 'Braun'),
    q(2, 'The design system Google introduced in 2014.', 'Material Design'),
    q(3, 'The height of a lowercase letter, measured without ascenders or descenders.', 'x-height'),
    q(3, 'The 2013 Apple OS release that dropped skeuomorphism for a flat look.', 'iOS 7'),
    q(3, 'The em dash is traditionally about as wide as this capital letter.', 'M'),
    q(4, 'This 1957 Swiss typeface was originally released as "Neue Haas Grotesk".', 'Helvetica'),
    q(4, 'He designed the "I ♥ NY" logo.', 'Milton Glaser'),
    q(4, 'The geometric sans serif Paul Renner designed in 1927.', 'Futura'),
    q(5, "Adrian Frutiger's 1957 sans serif family, famous for numbering its weights and widths instead of naming them.", 'Univers'),
    q(5, 'The formal name of the "Swiss Style" of graphic design.', 'International Typographic Style'),
    q(5, "Jan Tschichold's 1928 book that championed asymmetric, sans serif layouts.", 'Die neue Typographie (The New Typography)'),
  ],
  dailyDoubles: [
    q(3, "Paul Rand designed logos for IBM, ABC, and this company Steve Jobs founded after leaving Apple.", "NeXT"),
    q(3, "Saul Bass created the spiraling title sequence for this 1958 Hitchcock film.", "Vertigo"),
    q(4, "She designed the original Macintosh icons and the Chicago typeface.", "Susan Kare"),
    q(4, "Matthew Carter designed these two screen typefaces for Microsoft in the 1990s.", "Georgia and Verdana"),
    q(5, "He designed the London Underground typeface in 1916.", "Edward Johnston"),
    q(5, "The Dutch art movement founded in 1917 by Theo van Doesburg and Piet Mondrian.", "De Stijl"),
  ],
};
