import { q, type CategoryPoolDef } from '../types.ts';

/**
 * Prismatic system categories. Sources: ProductDesignAI/.claude/skills/component-*,
 * ProductDesignAI/knowledge (project_*, ds_*), ProductDesignAI CLAUDE.md and
 * CHANGELOG.md, Prismatic-Lens CLAUDE.md, README.md and governance/*.json.
 */

export const governanceCourt: CategoryPoolDef = {
  id: 'governance-court',
  title: 'Governance Court',
  description: 'The layout rules Lens enforces. Name the component or the limit.',
  type: 'text',
  group: 'prismatic',
  questions: [
    q(1, "This component must always be the last item on the page.", "Tabs"),
    q(1, "These two navigation containers can never appear on the same page.", "Tabs and the Stepper"),
    q(1, "This component can never be nested inside another one of itself.", "Accordion"),
    q(2, "This grid must always be first on the page.", "Employee Grid"),
    q(2, "The only component that can't be added unless a grid already exists.", "Prefilter"),
    q(2, "Settings Tables must always come before this component.", "The Grid"),
    q(3, "The only component allowed to sit above the Employee Grid.", "Message Panel"),
    q(3, "Adding a Prefilter limits the view to this many grids.", "One"),
    q(3, "The only component allowed on the same page as a Card Board.", "Message Panel"),
    q(3, "The fewest and the most columns a Comparison Table can have.", "Two and six"),
    q(3, "This Employee-only decorative hero must always be first on the page.", "Illustration Block"),
    q(4, "How many Accordions are allowed on a view that also has a grid?", "Two"),
    q(4, "The Document Manager must always come after this component.", "Employee Grid"),
    q(4, "Vertical Tabs can only go inside these two components.", "Tabs or a Stepper"),
    q(4, "The most buttons allowed in a Right Drawer button group.", "Three"),
    q(4, "This component can never be the last item on the page.", "Message Panel"),
    q(5, "With two Settings Tables on a view, the most rows each one can have.", "Eight"),
    q(5, "With three Settings Tables on a view, the most rows each one can have.", "Five"),
    q(5, "In a Grid Body, cards are only allowed in this column.", "Column two"),
    q(5, "The most grids allowed on a view, before other components lower the limit.", "Three"),
    q(5, "The most Integrations Card Grids allowed on one view.", "Three"),
    q(2, "The Accordion is not allowed in this experience type.", "Onboarding"),
    q(3, "How many Forms are allowed in one location?", "One"),
    q(3, "A Settings Table can't go in this side panel. Use bare inputs there instead.", "The Right Drawer"),
    q(4, "Name two components that hide the page title.", "Any two of: Employee Grid, Illustration Block, Craft Image, Question Form"),
    q(5, "How many grids are allowed inside a Question Block?", "One"),
  ],
  dailyDoubles: [
    q(3, "With only one Settings Table on a view, the most rows it can have.", "Fifteen"),
    q(3, "The most rows an Integrations Card Grid can have.", "Ten"),
    q(4, "The most details allowed on one Integrations Card.", "Eight"),
    q(4, "The most sections a single Question Form can have.", "Twenty"),
    q(5, "The most Question Forms allowed on one view.", "Three"),
    q(5, "The most columns a Form can have.", "Three"),
  ],
};

export const layoutLab: CategoryPoolDef = {
  id: 'layout-lab',
  title: 'Layout Lab',
  description: 'Page structure, widths, columns, and where things live on screen.',
  type: 'text',
  group: 'prismatic',
  questions: [
    q(1, 'Which side of the screen the Message Drawer slides in from.', 'The right'),
    q(1, 'How many columns an Admin form uses.', 'One (single column)'),
    q(1, 'Where form labels go relative to their inputs.', 'Above them'),
    q(2, 'Breadcrumbs sit between these two parts of the page.', 'Under the header and above the page title'),
    q(2, 'The form layout for employee-facing forms under 15–20 fields, with fields grouped side by side.', 'The Brick Layout'),
    q(2, 'The pattern used for admin forms with more than 15–20 fields.', 'The Settings Table'),
    q(3, 'The most columns a Brick Layout can have.', 'Three'),
    q(3, 'The max width of the Employee layout, in pixels.', '1500px'),
    q(3, 'The max width of the Admin layout, in pixels.', '1920px'),
    q(4, 'The column gap and row gap of the Brick Layout, in pixels.', '60px column gap, 24px row gap'),
    q(4, "The Grid Body's default two-column split, as a CSS ratio.", '2fr 1fr'),
    q(4, 'In the left navigation, icons appear only at this level.', 'L1'),
    q(4, 'Where Record Navigation goes, for browsing between records.', 'The right drawer'),
    q(5, 'Below this screen width, in pixels, the Comparison Table switches to stacked rows.', '667px'),
    q(5, 'On mobile, the left-nav toggle moves here.', 'The left side of the header'),
    q(5, 'The icon that marks dynamic, context-sensitive items in the left navigation.', 'A lightning bolt (Lightning Menu)'),
    q(5, "Breadcrumbs' left and right margins, in pixels.", '24px'),
    q(1, "Where the logo in the header must link to.", "The product's home"),
    q(2, "The header only holds global items. What does it never hold?", "Page-specific actions"),
    q(3, "The layout meant for complex data and high-density admin screens.", "The Admin Layout"),
    q(4, "In the left navigation, an item with no children acts as this.", "A direct link to its page"),
    q(5, "Brick Layouts can be embedded inside this, for grouped fields like an address.", "A Settings Table"),
  ],
  dailyDoubles: [
    q(3, "The Message Drawer adds \"Show More\" once a message passes this many lines.", "Four"),
    q(3, "At this screen width and below, the page background switches to --body-color, in pixels.", "1024px"),
    q(4, "The deepest a Tree Menu should go, in levels.", "Three to four"),
    q(4, "How many characters you type before Vertical Tabs start filtering.", "Three"),
    q(5, "The modal size for immersive experiences, and how wide it is.", "Full, 100% of the viewport"),
    q(5, "What the left navigation's expanded or collapsed state should do between sessions.", "Persist (be remembered)"),
  ],
};

export const componentConfidential: CategoryPoolDef = {
  id: 'component-confidential',
  title: 'Component Confidential',
  description: 'Read the description, name the component.',
  type: 'text',
  group: 'prismatic',
  questions: [
    q(1, 'My columns default to "To Do," "In Progress," and "Done."', 'Card Board'),
    q(1, "I show someone's photo, or their initials if there's no photo.", 'User Avatar'),
    q(1, "I'm a small status badge, like SUCCESS or WARNING.", 'Pill'),
    q(2, 'My types are info, warning, error, and success, and by default I show an animated robot.', 'Message Panel'),
    q(2, "I'm the card-style choice list you use instead of radio buttons when options are long or need icons.", 'Radio Panel'),
    q(2, "I capture a person's signature on a canvas.", 'Signature Pad'),
    q(3, "I'm a side panel, not a registered component. I hold inputs, button groups, key-values, then accordions.", 'Right Drawer'),
    q(3, 'I sit at the top of the page with its name, and I can be edited inline.', 'Page Title'),
    q(3, 'My default message is "AI Generated Summary."', 'AI Notice'),
    q(3, 'I slide in from the right when you click the notification bell.', 'Message Drawer'),
    q(3, 'I open from the user avatar and hold account settings, with Logout as my last section.', 'User Drawer (User Tools)'),
    q(4, 'My layouts include SINGLE_COLUMN and TWO_COLUMN_FIRST_LARGER.', 'Grid Body'),
    q(4, 'My default title is "Onboarding Tasks," and each item has a marker and a button.', 'Status Card'),
    q(4, 'My cards can be connected, pending, or disconnected, with at most six cards per row.', 'Integrations Card Grid'),
    q(4, 'I\'m a relative date picker, like "5 Days Before."', 'Date Offset'),
    q(4, 'My default header is "Login to your account," and I show a SOC logo.', 'Login Panel'),
    q(4, "I set an app's colors and logo for its whole visual identity.", 'Theme Builder'),
    q(5, 'I show parent and child items with checkboxes that can be checked, unchecked, or indeterminate.', 'Tree Menu'),
    q(5, 'I show a Social Security number as •••-••-####.', 'Masked SSN Input'),
    q(5, 'I show rating labels with an optional slider and an N/A toggle.', 'Scoring'),
    q(1, "I pop up at the top center of the screen and close myself after five seconds.", "Toast"),
    q(1, "I switch between two opposing states, like on and off.", "Toggle"),
    q(2, "I show your path, three items at most, and only appear after you start a New or Edit flow.", "Breadcrumbs"),
    q(2, "I gather several row actions into one control.", "Button Dropdown"),
    q(3, "I guide people through a multi-step wizard, and I should have five steps or fewer.", "Stepper"),
  ],
  dailyDoubles: [
    q(3, "I hold page-level actions that stay put no matter how far you scroll.", "Footer Bar"),
    q(3, "I'm an Admin-only library for uploading and managing documents.", "Document Manager"),
    q(4, "I'm a feature comparison matrix with two to six columns that stacks on mobile.", "Comparison Table"),
    q(4, "I always have a search bar at the top and an icon bar on the left.", "Left Navigation"),
    q(5, "I'm a hero image that can hold buttons, checkboxes, and radio panels, and I hide the page title.", "Craft Image"),
    q(5, "I'm a multi-section survey for onboarding, with sections that can show or hide based on answers.", "Question Form"),
  ],
};

export const sayItRight: CategoryPoolDef = {
  id: 'say-it-right',
  title: 'Say It Right',
  description: 'The approved words, labels, and messages.',
  type: 'text',
  group: 'prismatic',
  questions: [
    q(1, 'The approved label for making a copy of an item. Not "Copy," not "Clone."', 'Duplicate'),
    q(1, 'The three buttons in the unsaved-changes dialog.', 'Cancel, Continue, and Save & Continue'),
    q(1, 'The approved replacement for "Log in as Employee."', 'Impersonate Employee'),
    q(2, 'In the unsaved-changes dialog, the one primary button.', 'Save & Continue'),
    q(2, 'The two buttons in a delete confirmation.', 'Cancel and Delete'),
    q(2, 'The message a grid shows when a search finds nothing.', '"No results found"'),
    q(3, 'The title format for a delete modal.', '"Delete [Object Type]: [Name]", e.g. "Delete Employee: John Smith"'),
    q(3, "The only two allowed labels for a grid toolbar's primary button.", '"New" or "Add"'),
    q(3, 'Which status is approved: "In Progress" or "In Process"?', 'In Process'),
    q(3, 'The warning that must always accompany an AI badge.', '"AI-generated content may contain errors. Please verify important information."'),
    q(4, 'The standard body text of a delete confirmation.', '"Are you sure you want to delete this [item]? Once deleted, it cannot be recovered."'),
    q(4, 'The approved validation message for an empty required field.', '"This field is required."'),
    q(4, 'Where "Export" belongs instead of being a button next to "New."', 'In a dropdown in the table tools area, e.g. "Download as CSV"'),
    q(5, 'Do Import and Scheduling Job statuses say "Complete" or "Completed"?', 'Completed'),
    q(5, 'Name one of the terms the language rules ban outright.', 'Any of: clone, spoof, hard delete, impersonation mode'),
    q(5, 'The approved validation message for an invalid entry.', '"Please enter a valid value."'),
    q(1, "The two button labels banned in dialogs.", "Yes and No"),
    q(2, "This generic error message is banned.", "\"Invalid input.\""),
    q(2, "The approved label for viewing the system as a client.", "Impersonate Client"),
    q(3, "The AI badge only goes on this kind of content.", "AI-generated or AI-assisted content"),
    q(4, "A footer button label should never combine more than one of these.", "Verbs (one action per label)"),
  ],
  dailyDoubles: [
    q(3, "The approved placeholder text for a grid search box.", "\"Search\""),
    q(3, "Name two of the approved AI badge labels.", "Any two of: AI Generated Summary, Content, Response, Analysis, Recommendation"),
    q(4, "Why \"Copy\" was rejected as a label.", "It's ambiguous with copying to the clipboard"),
    q(4, "Why the label says \"Impersonate\" instead of \"Log in as.\"", "Impersonation may be read-only"),
    q(5, "The style guide's example of an action label to use on a footer button instead of \"Yes.\"", "\"Delete Report\""),
    q(5, "Name one status that uses \"Complete\" rather than \"Completed.\"", "Any of: AE, Enrollment, Task"),
  ],
};

export const gridsAndTables: CategoryPoolDef = {
  id: 'grids-tables',
  title: 'Grids & Tables',
  description: 'Row actions, status columns, checkboxes, and refresh.',
  type: 'text',
  group: 'prismatic',
  questions: [
    q(1, "The control to use when a grid row has just one action.", "An inline button"),
    q(1, "The control to use when a grid row has more than one action.", "A button dropdown"),
    q(1, "Every table in Prismatic always includes this row.", "A header row"),
    q(2, "Where the asterisk goes for a required table column.", "In the column header only, right of the label"),
    q(2, "What the checkbox in a table header controls.", "The whole column (select all rows)"),
    q(2, "What row checkboxes in a table are for.", "Selecting rows for bulk actions"),
    q(3, "Where primary actions go in a row's action dropdown.", "First"),
    q(3, "Where destructive actions go in a row's action dropdown.", "Last"),
    q(3, "Every status type in a grid must appear in this column.", "The Status column"),
    q(3, "The status type for read-only, system-determined statuses.", "A static status badge"),
    q(4, "The status type for quantifiable, multi-step processes.", "A progress bar"),
    q(4, "What a manual-refresh grid should display so people know how fresh the data is.", "A \"last updated\" timestamp"),
    q(4, "The keyboard shortcuts that refresh a grid that has focus.", "F5 or Cmd/Ctrl + R"),
    q(5, "The status type for showing several attributes at once.", "A multi-status indicator"),
    q(5, "How the width of an action column should be set.", "Fixed, sized to fit the widest control"),
    q(5, "Where the refresh button goes on a manual-refresh grid.", "In the toolbar"),
    q(3, "Manual refresh is meant for this kind of grid.", "Performance-heavy grids with large datasets"),
    q(4, "A column only gets the required indicator when it is required for this.", "Row validity"),
    q(4, "Besides a visual bar, progress bars should include these.", "Numeric indicators (with details on hover)"),
    q(5, "A required-column indicator must never rely on this alone.", "Color"),
  ],
  dailyDoubles: [
    q(3, "How actions in a row dropdown should be ordered.", "By how often they are used, with related actions grouped by separators"),
    q(3, "Should real-time, critical data use a manual-refresh grid?", "No. Use automatic refresh"),
    q(4, "The three things a grid must keep after a manual refresh.", "Sorting, filtering, and selection"),
    q(4, "The two things a grid must do while it refreshes.", "Show a loading indicator and block duplicate requests"),
    q(5, "What each indicator in a multi-status indicator needs.", "Its own tooltip"),
    q(5, "When to use a status dropdown instead of a badge.", "When people need to set or change the status themselves"),
  ],
};
